enum PluginKind {
    AuthenticationPlugin = "AuthenticationPlugin",
    AuthorizationPlugin = "AuthorizationPlugin",
    // AvailabilityPlugin = "AvailabilityPlugin",
    BackupPlugin = "BackupPlugin",
    CachePlugin = "CachePlugin",
    ChatPlugin = "ChatPlugin",
    CircuitBreaker = "CircuitBreaker",
    ConfigurationPlugin = "ConfigurationPlugin",
    ContainerPlugin = "ContainerPlugin",
    ConsolePlugin = "ConsolePlugin",
    // DiscoveryPlugin = "DiscoveryPlugin",
    EmailPlugin = "EmailPlugin",
    ExecutionPlugin = "ExecutionPlugin",
    FaxPlugin = "FaxPlugin",
    HookPlugin = "HookPlugin",
    InitPlugin = "InitPlugin",
    LicensingPlugin = "LicensingPlugin",
    ListenerPlugin = "ListenerPlugin",
    LoggingPlugin = "LoggingPlugin",
    MMSPlugin = "MMSPlugin",
    NotificationPlugin = "NotificationPlugin",
    // ReplicationPlugin = "ReplicationPlugin",
    SearchPlugin = "SearchPlugin",
    StoragePlugin = "StoragePlugin",
    QueuePlugin = "QueuePlugin",
    QuotaPlugin = "QuotaPlugin",
    VaultPlugin = "VaultPlugin",
}

export default PluginKind;
